version: '3'

services:
  hello-world:
    image: hello-world
    build: 
      context: .
    ports:
      - 80:8080
    logging:
      driver: awslogs
      options:
        awslogs-region: "us-west-1"
        awslogs-group: "log-group-${HOSTNAME}"
        awslogs-stream: "log-stream"